[package]
name = "denysubs"
version = "0.1.0"
authors = ["foresterre <garm@ilumeo.com>"]
edition = "2018"
license-file = "../bbb.txt" #outside the crate

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
